version: 0.2

phases:
  install:
    commands:
      - echo "No installation commands needed." 

  pre_build:
    commands:
      - echo "Executing the PreBuild Commands"
      - aws sts get-caller-identity
      - aws ecr describe-repositories --repository-names movieapp || echo "Repository does not exist"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 872515248362.dkr.ecr.us-east-2.amazonaws.com
      
  build:
    commands:
      - echo "Executing the Build Commands"
      - ls -la
      - docker build -t movieapp:v$CODEBUILD_BUILD_NUMBER .
      
  post_build:
    commands:
      - echo "Executing the PostBuild Commands"
      - docker tag movieapp:v$CODEBUILD_BUILD_NUMBER 872515248362.dkr.ecr.us-east-2.amazonaws.com/movieapp:latest
      - docker tag movieapp:v$CODEBUILD_BUILD_NUMBER 872515248362.dkr.ecr.us-east-2.amazonaws.com/movieapp:v$CODEBUILD_BUILD_NUMBER
      - docker push 872515248362.dkr.ecr.us-east-2.amazonaws.com/movieapp:latest
      - docker push 872515248362.dkr.ecr.us-east-2.amazonaws.com/movieapp:v$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - '**/*'

    
