apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: movieapp-cluster         # Name of your cluster
  region: us-east-1              # AWS region (Ohio)
  version: "1.31"                # Kubernetes version

nodeGroups:
  - name: movieapp-ng            # Name of the node group
    instanceType: t2.medium      # EC2 instance type for nodes
    desiredCapacity: 1            # Desired number of nodes
    minSize: 1                    # Minimum number of nodes
    maxSize: 5                    # Maximum number of nodes
    volumeSize: 20                # EBS volume size (in GB)
    volumeType: gp2               # EBS volume type
    ssh:
      allow: true                 # Enables SSH access
      publicKeyName: Harsha_cloud # Specify your SSH key here
    privateNetworking: false

iam:
  withOIDC: true                 # Enables OIDC integration for IAM roles
  serviceRoleARN:                # (Optional) IAM role for the EKS cluster

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

vpc:
  nat:
    gateway: Single

kubernetesNetworkConfig:
  ipFamily: IPv4

addons:
  - name: vpc-cni
    version: latest
