apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp
  labels:
    app: movieapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movieapp
  template:
    metadata:
      labels:
        app: movieapp
    spec:
      containers:
      - name: movieapp
        image: 872515248362.dkr.ecr.us-east-2.amazonaws.com/movieapp
        ports:
        - containerPort: 80
